version: "3.7"

services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: distribunetes
    volumes:
      - ./backend/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: bash -c "yarn dev"
    container_name: backend
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - ./backend/:/home/node/
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    command: bash -c "yarn start"
    container_name: frontend
    restart: on-failure
    stdin_open: true
    env_file:
      - frontend/variables.env
    links:
      - backend
    depends_on:
      - backend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/home/node